version: '3'
services:
  db:
    image: 'mariadb:latest'
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: 'rootpwd'
      MARIADB_DATABASE: 'permissions'
      MARIADB_USER: 'load'
      MARIADB_PASSWORD: 'loadpwd'
    expose:
      - "3306"
    volumes:
      - "./data:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  load:
    image: ghcr.io/styrainc/load-private:1.3.0-66-debug
    ports:
      - "8181:8181"
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "--addr=0.0.0.0:8181"
      - "/policy"
    environment:
      STYRA_LOAD_LICENSE_KEY: ${STYRA_LOAD_LICENSE_KEY}
    volumes:
      - "./policy:/policy"

